/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSL */

#ifndef _Included_com_wolfssl_WolfSSL
#define _Included_com_wolfssl_WolfSSL
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_WolfSSL_SSL_ERROR_NONE
#define com_wolfssl_WolfSSL_SSL_ERROR_NONE 0L
#undef com_wolfssl_WolfSSL_SSL_FAILURE
#define com_wolfssl_WolfSSL_SSL_FAILURE 0L
#undef com_wolfssl_WolfSSL_SSL_SUCCESS
#define com_wolfssl_WolfSSL_SSL_SUCCESS 1L
#undef com_wolfssl_WolfSSL_SSL_SHUTDOWN_NOT_DONE
#define com_wolfssl_WolfSSL_SSL_SHUTDOWN_NOT_DONE 2L
#undef com_wolfssl_WolfSSL_SSL_BAD_CERTTYPE
#define com_wolfssl_WolfSSL_SSL_BAD_CERTTYPE -8L
#undef com_wolfssl_WolfSSL_SSL_BAD_STAT
#define com_wolfssl_WolfSSL_SSL_BAD_STAT -7L
#undef com_wolfssl_WolfSSL_SSL_BAD_PATH
#define com_wolfssl_WolfSSL_SSL_BAD_PATH -6L
#undef com_wolfssl_WolfSSL_SSL_BAD_FILETYPE
#define com_wolfssl_WolfSSL_SSL_BAD_FILETYPE -5L
#undef com_wolfssl_WolfSSL_SSL_BAD_FILE
#define com_wolfssl_WolfSSL_SSL_BAD_FILE -4L
#undef com_wolfssl_WolfSSL_SSL_NOT_IMPLEMENTED
#define com_wolfssl_WolfSSL_SSL_NOT_IMPLEMENTED -3L
#undef com_wolfssl_WolfSSL_SSL_UNKNOWN
#define com_wolfssl_WolfSSL_SSL_UNKNOWN -2L
#undef com_wolfssl_WolfSSL_SSL_FATAL_ERROR
#define com_wolfssl_WolfSSL_SSL_FATAL_ERROR -1L
#undef com_wolfssl_WolfSSL_SSL_FILETYPE_ASN1
#define com_wolfssl_WolfSSL_SSL_FILETYPE_ASN1 2L
#undef com_wolfssl_WolfSSL_SSL_FILETYPE_PEM
#define com_wolfssl_WolfSSL_SSL_FILETYPE_PEM 1L
#undef com_wolfssl_WolfSSL_SSL_FILETYPE_DEFAULT
#define com_wolfssl_WolfSSL_SSL_FILETYPE_DEFAULT 2L
#undef com_wolfssl_WolfSSL_SSL_FILETYPE_RAW
#define com_wolfssl_WolfSSL_SSL_FILETYPE_RAW 3L
#undef com_wolfssl_WolfSSL_SSL_VERIFY_NONE
#define com_wolfssl_WolfSSL_SSL_VERIFY_NONE 0L
#undef com_wolfssl_WolfSSL_SSL_VERIFY_PEER
#define com_wolfssl_WolfSSL_SSL_VERIFY_PEER 1L
#undef com_wolfssl_WolfSSL_SSL_VERIFY_FAIL_IF_NO_PEER_CERT
#define com_wolfssl_WolfSSL_SSL_VERIFY_FAIL_IF_NO_PEER_CERT 2L
#undef com_wolfssl_WolfSSL_SSL_VERIFY_CLIENT_ONCE
#define com_wolfssl_WolfSSL_SSL_VERIFY_CLIENT_ONCE 4L
#undef com_wolfssl_WolfSSL_SSL_SESS_CACHE_OFF
#define com_wolfssl_WolfSSL_SSL_SESS_CACHE_OFF 30L
#undef com_wolfssl_WolfSSL_SSL_SESS_CACHE_CLIENT
#define com_wolfssl_WolfSSL_SSL_SESS_CACHE_CLIENT 31L
#undef com_wolfssl_WolfSSL_SSL_SESS_CACHE_SERVER
#define com_wolfssl_WolfSSL_SSL_SESS_CACHE_SERVER 32L
#undef com_wolfssl_WolfSSL_SSL_SESS_CACHE_BOTH
#define com_wolfssl_WolfSSL_SSL_SESS_CACHE_BOTH 33L
#undef com_wolfssl_WolfSSL_SSL_SESS_CACHE_NO_AUTO_CLEAR
#define com_wolfssl_WolfSSL_SSL_SESS_CACHE_NO_AUTO_CLEAR 34L
#undef com_wolfssl_WolfSSL_SSL_SESS_CACHE_NO_INTERNAL_LOOKUP
#define com_wolfssl_WolfSSL_SSL_SESS_CACHE_NO_INTERNAL_LOOKUP 35L
#undef com_wolfssl_WolfSSL_SSL_ERROR_WANT_READ
#define com_wolfssl_WolfSSL_SSL_ERROR_WANT_READ 2L
#undef com_wolfssl_WolfSSL_SSL_ERROR_WANT_WRITE
#define com_wolfssl_WolfSSL_SSL_ERROR_WANT_WRITE 3L
#undef com_wolfssl_WolfSSL_SSL_ERROR_WANT_CONNECT
#define com_wolfssl_WolfSSL_SSL_ERROR_WANT_CONNECT 7L
#undef com_wolfssl_WolfSSL_SSL_ERROR_WANT_ACCEPT
#define com_wolfssl_WolfSSL_SSL_ERROR_WANT_ACCEPT 8L
#undef com_wolfssl_WolfSSL_SSL_ERROR_SYSCALL
#define com_wolfssl_WolfSSL_SSL_ERROR_SYSCALL 5L
#undef com_wolfssl_WolfSSL_SSL_ERROR_WANT_X509_LOOKUP
#define com_wolfssl_WolfSSL_SSL_ERROR_WANT_X509_LOOKUP 83L
#undef com_wolfssl_WolfSSL_SSL_ERROR_ZERO_RETURN
#define com_wolfssl_WolfSSL_SSL_ERROR_ZERO_RETURN 6L
#undef com_wolfssl_WolfSSL_SSL_ERROR_SSL
#define com_wolfssl_WolfSSL_SSL_ERROR_SSL 85L
#undef com_wolfssl_WolfSSL_WOLFSSL_CRL_CHECKALL
#define com_wolfssl_WolfSSL_WOLFSSL_CRL_CHECKALL 1L
#undef com_wolfssl_WolfSSL_WOLFSSL_OCSP_URL_OVERRIDE
#define com_wolfssl_WolfSSL_WOLFSSL_OCSP_URL_OVERRIDE 1L
#undef com_wolfssl_WolfSSL_WOLFSSL_OCSP_NO_NONCE
#define com_wolfssl_WolfSSL_WOLFSSL_OCSP_NO_NONCE 2L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_GENERAL
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_GENERAL -1L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_WANT_READ
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_WANT_READ -2L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_WANT_WRITE
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_WANT_WRITE -2L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_CONN_RST
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_CONN_RST -3L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_ISR
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_ISR -4L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_CONN_CLOSE
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_CONN_CLOSE -5L
#undef com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_TIMEOUT
#define com_wolfssl_WolfSSL_WOLFSSL_CBIO_ERR_TIMEOUT -6L
#undef com_wolfssl_WolfSSL_WOLFSSL_SERVER_END
#define com_wolfssl_WolfSSL_WOLFSSL_SERVER_END 0L
#undef com_wolfssl_WolfSSL_WOLFSSL_CLIENT_END
#define com_wolfssl_WolfSSL_WOLFSSL_CLIENT_END 1L
#undef com_wolfssl_WolfSSL_WOLFSSL_BLOCK_TYPE
#define com_wolfssl_WolfSSL_WOLFSSL_BLOCK_TYPE 2L
#undef com_wolfssl_WolfSSL_WOLFSSL_STREAM_TYPE
#define com_wolfssl_WolfSSL_WOLFSSL_STREAM_TYPE 3L
#undef com_wolfssl_WolfSSL_WOLFSSL_AEAD_TYPE
#define com_wolfssl_WolfSSL_WOLFSSL_AEAD_TYPE 4L
#undef com_wolfssl_WolfSSL_WOLFSSL_TLS_HMAC_INNER_SZ
#define com_wolfssl_WolfSSL_WOLFSSL_TLS_HMAC_INNER_SZ 13L
#undef com_wolfssl_WolfSSL_GEN_COOKIE_E
#define com_wolfssl_WolfSSL_GEN_COOKIE_E -277L
#undef com_wolfssl_WolfSSL_SSL_SENT_SHUTDOWN
#define com_wolfssl_WolfSSL_SSL_SENT_SHUTDOWN 1L
#undef com_wolfssl_WolfSSL_SSL_RECEIVED_SHUTDOWN
#define com_wolfssl_WolfSSL_SSL_RECEIVED_SHUTDOWN 2L
#undef com_wolfssl_WolfSSL_SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER
#define com_wolfssl_WolfSSL_SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER 4L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_SSLv2
#define com_wolfssl_WolfSSL_SSL_OP_NO_SSLv2 8L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_SSLv3
#define com_wolfssl_WolfSSL_SSL_OP_NO_SSLv3 4096L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1
#define com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1 8192L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1_1
#define com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1_1 67108864L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1_2
#define com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1_2 134217728L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_COMPRESSION
#define com_wolfssl_WolfSSL_SSL_OP_NO_COMPRESSION 268435456L
#undef com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1_3
#define com_wolfssl_WolfSSL_SSL_OP_NO_TLSv1_3 536870912L
#undef com_wolfssl_WolfSSL_SSL_HANDSHAKE_FAILURE
#define com_wolfssl_WolfSSL_SSL_HANDSHAKE_FAILURE 101L
#undef com_wolfssl_WolfSSL_SSL_R_TLSV1_ALERT_UNKNOWN_CA
#define com_wolfssl_WolfSSL_SSL_R_TLSV1_ALERT_UNKNOWN_CA 102L
#undef com_wolfssl_WolfSSL_SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN
#define com_wolfssl_WolfSSL_SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN 103L
#undef com_wolfssl_WolfSSL_SSL_R_SSLV3_ALERT_BAD_CERTIFICATE
#define com_wolfssl_WolfSSL_SSL_R_SSLV3_ALERT_BAD_CERTIFICATE 104L
#undef com_wolfssl_WolfSSL_WOLFSSL_CRL_MONITOR
#define com_wolfssl_WolfSSL_WOLFSSL_CRL_MONITOR 1L
#undef com_wolfssl_WolfSSL_WOLFSSL_CRL_START_MON
#define com_wolfssl_WolfSSL_WOLFSSL_CRL_START_MON 2L
#undef com_wolfssl_WolfSSL_BAD_MUTEX_ERROR
#define com_wolfssl_WolfSSL_BAD_MUTEX_ERROR -256L
#undef com_wolfssl_WolfSSL_BAD_PATH_ERROR
#define com_wolfssl_WolfSSL_BAD_PATH_ERROR -258L
#undef com_wolfssl_WolfSSL_MONITOR_RUNNING_E
#define com_wolfssl_WolfSSL_MONITOR_RUNNING_E -263L
#undef com_wolfssl_WolfSSL_THREAD_CREATE_E
#define com_wolfssl_WolfSSL_THREAD_CREATE_E -264L
#undef com_wolfssl_WolfSSL_CACHE_MATCH_ERROR
#define com_wolfssl_WolfSSL_CACHE_MATCH_ERROR -280L
#undef com_wolfssl_WolfSSL_MEMORY_E
#define com_wolfssl_WolfSSL_MEMORY_E -125L
#undef com_wolfssl_WolfSSL_BUFFER_E
#define com_wolfssl_WolfSSL_BUFFER_E -132L
#undef com_wolfssl_WolfSSL_ASN_INPUT_E
#define com_wolfssl_WolfSSL_ASN_INPUT_E -154L
#undef com_wolfssl_WolfSSL_BAD_FUNC_ARG
#define com_wolfssl_WolfSSL_BAD_FUNC_ARG -173L
#undef com_wolfssl_WolfSSL_NOT_COMPILED_IN
#define com_wolfssl_WolfSSL_NOT_COMPILED_IN -174L
#undef com_wolfssl_WolfSSL_NO_PASSWORD
#define com_wolfssl_WolfSSL_NO_PASSWORD -176L
#undef com_wolfssl_WolfSSL_MD5
#define com_wolfssl_WolfSSL_MD5 0L
#undef com_wolfssl_WolfSSL_SHA
#define com_wolfssl_WolfSSL_SHA 1L
#undef com_wolfssl_WolfSSL_SHA256
#define com_wolfssl_WolfSSL_SHA256 2L
#undef com_wolfssl_WolfSSL_SHA512
#define com_wolfssl_WolfSSL_SHA512 4L
#undef com_wolfssl_WolfSSL_SHA384
#define com_wolfssl_WolfSSL_SHA384 5L
#undef com_wolfssl_WolfSSL_DSAk
#define com_wolfssl_WolfSSL_DSAk 515L
#undef com_wolfssl_WolfSSL_RSAk
#define com_wolfssl_WolfSSL_RSAk 645L
#undef com_wolfssl_WolfSSL_NTRUk
#define com_wolfssl_WolfSSL_NTRUk 274L
#undef com_wolfssl_WolfSSL_ECDSAk
#define com_wolfssl_WolfSSL_ECDSAk 518L
#undef com_wolfssl_WolfSSL_ED25519k
#define com_wolfssl_WolfSSL_ED25519k 256L
/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_WolfSSL_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumNULL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumNULL
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumRC4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumRC4
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumRC2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumRC2
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumDES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumDES
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnum3DES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnum3DES
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumDES40
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumDES40
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumIDEA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumIDEA
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumAES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumAES
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumAESGCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumAESGCM
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumAESCCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumAESCCM
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumCHACHA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumCHACHA
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumCAMELLIA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumCAMELLIA
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumHC128
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumHC128
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getBulkCipherAlgorithmEnumRABBIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getBulkCipherAlgorithmEnumRABBIT
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getEnabledCipherSuites
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSL_getEnabledCipherSuites
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getEnabledCipherSuitesIana
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSL_getEnabledCipherSuitesIana
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_WolfSSL_TLSv1Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv11Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_WolfSSL_TLSv11Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv12Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_WolfSSL_TLSv12Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv13Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_WolfSSL_TLSv13Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    EccEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_WolfSSL_EccEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    RsaEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_WolfSSL_RsaEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    SSLv3_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_SSLv3_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    SSLv3_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_SSLv3_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_1_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_11_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_1_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_11_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_1_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_11_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_2_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_12_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_2_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_12_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_2_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_12_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    TLSv1_3_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_TLSv1_13_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    DTLSv1_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_DTLSv1_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    DTLSv1_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_DTLSv1_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    DTLSv1_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_DTLSv1_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    DTLSv1_2_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_DTLSv1_12_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    DTLSv1_2_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_DTLSv1_12_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    DTLSv1_2_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_DTLSv1_12_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    SSLv23_Method
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_SSLv23_1Method
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    SSLv23_ServerMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_SSLv23_1ServerMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    SSLv23_ClientMethod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSL_SSLv23_1ClientMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getErrorString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSL_getErrorString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_cleanup
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    debuggingON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_debuggingON
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    debuggingOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_WolfSSL_debuggingOFF
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    setLoggingCb
 * Signature: (Lcom/wolfssl/WolfSSLLoggingCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_setLoggingCb
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    memsaveSessionCache
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_memsaveSessionCache
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    memrestoreSessionCache
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_memrestoreSessionCache
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getSessionCacheMemsize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getSessionCacheMemsize
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getPkcs8TraditionalOffset
 * Signature: ([BJJ)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getPkcs8TraditionalOffset
  (JNIEnv *, jclass, jbyteArray, jlong, jlong);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    x509_getDer
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfSSL_x509_1getDer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getHmacMaxSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_getHmacMaxSize
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledCRL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledCRL
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledCRLMonitor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledCRLMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledOCSP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledOCSP
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledPSK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledPSK
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledDTLS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledDTLS
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledAtomicUser
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledAtomicUser
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    isEnabledPKCallbacks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSL_isEnabledPKCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getProtocols
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_WolfSSL_getProtocols
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSL
 * Method:    getProtocols
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_WolfSSL_getProtocolsMask
  (JNIEnv*, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
