/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSLCertManager */

#ifndef _Included_com_wolfssl_WolfSSLCertManager
#define _Included_com_wolfssl_WolfSSLCertManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfSSLCertManager
 * Method:    CertManagerNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSLCertManager_CertManagerNew
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSLCertManager
 * Method:    CertManagerFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_WolfSSLCertManager_CertManagerFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCertManager
 * Method:    CertManagerLoadCA
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCertManager_CertManagerLoadCA
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_wolfssl_WolfSSLCertManager
 * Method:    CertManagerLoadCABuffer
 * Signature: (J[BJI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCertManager_CertManagerLoadCABuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint);

/*
 * Class:     com_wolfssl_WolfSSLCertManager
 * Method:    CertManagerVerifyBuffer
 * Signature: (J[BJI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCertManager_CertManagerVerifyBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
