/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfCryptEccKey */

#ifndef _Included_com_wolfssl_WolfCryptEccKey
#define _Included_com_wolfssl_WolfCryptEccKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfCryptEccKey
 * Method:    EccPublicKeyToDer
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfCryptEccKey_EccPublicKeyToDer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptEccKey
 * Method:    EccPrivateKeyToDer
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfCryptEccKey_EccPrivateKeyToDer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptEccKey
 * Method:    EccPrivateKeyToPKCS8
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfCryptEccKey_EccPrivateKeyToPKCS8
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
