/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSL_TLS_VERSION */

#ifndef _Included_com_wolfssl_WolfSSL_TLS_VERSION
#define _Included_com_wolfssl_WolfSSL_TLS_VERSION
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
