/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfCryptECC */

#ifndef _Included_com_wolfssl_WolfCryptECC
#define _Included_com_wolfssl_WolfCryptECC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfCryptECC
 * Method:    doVerify
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J[I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptECC_doVerify
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong, jobject, jlong, jintArray);

/*
 * Class:     com_wolfssl_WolfCryptECC
 * Method:    doSign
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;[JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptECC_doSign
  (JNIEnv *, jobject, jobject, jlong, jobject, jlongArray, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
