/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfCryptRSA */

#ifndef _Included_com_wolfssl_WolfCryptRSA
#define _Included_com_wolfssl_WolfCryptRSA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfCryptRSA
 * Method:    doSign
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;[ILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptRSA_doSign
  (JNIEnv *, jobject, jobject, jlong, jobject, jintArray, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptRSA
 * Method:    doVerify
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptRSA_doVerify
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptRSA
 * Method:    doEnc
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;[ILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptRSA_doEnc
  (JNIEnv *, jobject, jobject, jlong, jobject, jintArray, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptRSA
 * Method:    doDec
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptRSA_doDec
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptRSA
 * Method:    doPssSign
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;[IIILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptRSA_doPssSign
  (JNIEnv *, jobject, jobject, jlong, jobject, jintArray, jint, jint, jobject, jlong);

/*
 * Class:     com_wolfssl_WolfCryptRSA
 * Method:    doPssVerify
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JIILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfCryptRSA_doPssVerify
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong, jint, jint, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
