/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSLCRL */

#ifndef _Included_com_wolfssl_WolfSSLCRL
#define _Included_com_wolfssl_WolfSSLCRL
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_WolfSSLCRL_serialVersionUID
#define com_wolfssl_WolfSSLCRL_serialVersionUID 1LL
#undef com_wolfssl_WolfSSLCRL_ASN_UTC_TIME
#define com_wolfssl_WolfSSLCRL_ASN_UTC_TIME 23L
#undef com_wolfssl_WolfSSLCRL_ASN_GENERALIZED_TIME
#define com_wolfssl_WolfSSLCRL_ASN_GENERALIZED_TIME 24L
#undef com_wolfssl_WolfSSLCRL_CTC_DATE_SIZE
#define com_wolfssl_WolfSSLCRL_CTC_DATE_SIZE 32L
#undef com_wolfssl_WolfSSLCRL_ASN1_TIME_STRUCT_SIZE
#define com_wolfssl_WolfSSLCRL_ASN1_TIME_STRUCT_SIZE 40L
#undef com_wolfssl_WolfSSLCRL_ASN1_UTC_YEAR_MIN
#define com_wolfssl_WolfSSLCRL_ASN1_UTC_YEAR_MIN 1950L
#undef com_wolfssl_WolfSSLCRL_ASN1_UTC_YEAR_MAX
#define com_wolfssl_WolfSSLCRL_ASN1_UTC_YEAR_MAX 2049L
#undef com_wolfssl_WolfSSLCRL_EVP_PKEY_RSA
#define com_wolfssl_WolfSSLCRL_EVP_PKEY_RSA 16L
#undef com_wolfssl_WolfSSLCRL_EVP_PKEY_EC
#define com_wolfssl_WolfSSLCRL_EVP_PKEY_EC 18L
/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_set_version
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1set_1version
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_set_issuer_name
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1set_1issuer_1name
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_set_lastUpdate
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1set_1lastUpdate
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_set_nextUpdate
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1set_1nextUpdate
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_add_revoked
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1add_1revoked
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_add_revoked_cert
 * Signature: (J[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1add_1revoked_1cert
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_sign
 * Signature: (JI[BILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1sign
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jstring);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    write_X509_CRL
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_write_1X509_1CRL
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_print
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_lastUpdate
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1lastUpdate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_nextUpdate
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1nextUpdate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_der
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1der
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_pem
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1pem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_signature
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1signature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_load_buffer
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1load_1buffer
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_load_file
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1load_1file
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_issuer_name_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1issuer_1name_1string
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_signature_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1signature_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_get_signature_nid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1get_1signature_1nid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLCRL
 * Method:    X509_CRL_verify
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLCRL_X509_1CRL_1verify
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
