/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSLSessionInfo */

#ifndef _Included_com_wolfssl_WolfSSLSessionInfo
#define _Included_com_wolfssl_WolfSSLSessionInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfSSLSessionInfo
 * Method:    SESSION_set_timeout
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSLSessionInfo_SESSION_1set_1timeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_wolfssl_WolfSSLSessionInfo
 * Method:    SESSION_get_timeout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_WolfSSLSessionInfo_SESSION_1get_1timeout
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
