/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSLNameConstraints */

#ifndef _Included_com_wolfssl_WolfSSLNameConstraints
#define _Included_com_wolfssl_WolfSSLNameConstraints
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfSSLNameConstraints
 * Method:    wolfSSL_NAME_CONSTRAINTS_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_WolfSSLNameConstraints_wolfSSL_1NAME_1CONSTRAINTS_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLNameConstraints
 * Method:    wolfSSL_NAME_CONSTRAINTS_permittedNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLNameConstraints_wolfSSL_1NAME_1CONSTRAINTS_1permittedNum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLNameConstraints
 * Method:    wolfSSL_NAME_CONSTRAINTS_excludedNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLNameConstraints_wolfSSL_1NAME_1CONSTRAINTS_1excludedNum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_WolfSSLNameConstraints
 * Method:    wolfSSL_GENERAL_SUBTREE_getBaseType
 * Signature: (JZI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLNameConstraints_wolfSSL_1GENERAL_1SUBTREE_1getBaseType
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     com_wolfssl_WolfSSLNameConstraints
 * Method:    wolfSSL_GENERAL_SUBTREE_getBaseValue
 * Signature: (JZI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_WolfSSLNameConstraints_wolfSSL_1GENERAL_1SUBTREE_1getBaseValue
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     com_wolfssl_WolfSSLNameConstraints
 * Method:    wolfSSL_NAME_CONSTRAINTS_check_name
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_WolfSSLNameConstraints_wolfSSL_1NAME_1CONSTRAINTS_1check_1name
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
