/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_WolfSSLX509StoreCtx */

#ifndef _Included_com_wolfssl_WolfSSLX509StoreCtx
#define _Included_com_wolfssl_WolfSSLX509StoreCtx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_WolfSSLX509StoreCtx
 * Method:    X509_STORE_CTX_getDerCerts
 * Signature: (J)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_WolfSSLX509StoreCtx_X509_1STORE_1CTX_1getDerCerts
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
